name: Kokoro
options:
  bundleIdPrefix: com.fluidaudio
  deploymentTarget:
    iOS: '17.0'
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.fluidaudio.tts
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: 5.10
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_BITCODE: NO
    SUPPORTED_PLATFORMS: iphoneos
    SUPPORTS_MACCATALYST: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO

targets:
  Kokoro:
    type: application
    platform: iOS
    sources:
      - path: Kokoro/Sources
        name: Sources
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Kokoro/Resources
        name: Resources
        excludes:
          - Info.plist
    info:
      path: Kokoro/Resources/Info.plist
      properties:
        CFBundleDisplayName: Kokoro
        CFBundleName: Kokoro
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: FluidAudio
        product: FluidAudio
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: Kokoro
        PRODUCT_BUNDLE_IDENTIFIER: com.fluidaudio.tts
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
        Release:
          ONLY_ACTIVE_ARCH: NO

packages:
  FluidAudio:
    path: ../FluidAudio-git

schemes:
  Kokoro:
    build:
      targets:
        Kokoro: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
